name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./01 Starting Project"
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # this stores it in a GitHub folder 
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm 
          # this is used to retrieve it but also when it is discarded - needs a dynamic element 
          # the specified folder is where dependencies and versions of this project are stored
          # whenever something changes in the file, the hash being produced will not be the same as before 
          # npm ci command below now uses this folder / if not it installes them 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json' )}}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./01 Starting Project"
    outputs:
      # accesses the steps context value, directing towards the variable we're interested in steps.<id-given>.outputs.<filename('filename={}')>
      # output for the overall job 
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # uses the same cache as the one intialised above
      # manages a central cache available across different workflows 
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm 
          key: deps-node-modules-${{ hashFiles('**/package-lock.json' )}}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      # this does not automatically make the 'variable' (name code) available
      # we write the output from the name of output file (script-file) into a special file created in the environment where the job runs, where the output key value pair resides, stored in this variable (GITHUB_OUTPUT)
      - name: Publish JS filename
        id: publish
        # another syntax type that may be used echo '::set-output name=script-file::{}' ';' - not be supported by GitHub anymore
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        # @v3 is not supported anymore?
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: ./01 Starting Project/dist 
          # multiple paths and files to be stored, though not necessary in this case 
          # path: |
          #   ./01 Starting Project/dist
          #   ./01 Starting Project/package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents 
        run: ls
      # to use outputs from other objects / jobs - we use needs bc the build job is already specified there 
      # passes simple data between jobs 
      # becomes especially important once we start building custom actions
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
